target("demo")
    set_kind("binary")
    add_includedirs("src")
    add_files("src/*.cpp")
    add_includedirs("res")
    add_files("res/*.cpp")
    add_files("*.cpp")
    add_packages("fltk")

on_load(function (target)
    target:add("syslinks", "fltk")
end)
